name: "Setup awesome-ci tooling"
description: "Setup awesome-ci as a CI tool in the latest stable version"
runs:
  using: "composite"
  steps:
    - name: Get Build infos
      shell: bash
      run: |
        wget $DL_URL -O awesome-ci
        chmod +x awesome-ci
        echo "PATH=$(pwd)/awesome-ci:$PATH" >> $GITHUB_ENV
      env:
        DL_URL: https://github.com/eksrvb/awesome-ci/releases/latest/download/awesome-ci
