name: Build PR

on:
  push:
    branches-ignore:
      - "master"
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build
        run: go build -v
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          path: awesome-ci
      - name: Dryrun dummy Release
        run: ./awesome-ci createRelease -patchLevel bugfix -dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
