name: Build PR

on:
  push:
    branches-ignore:
      - "main"
      - "docu/**"
    paths-ignore:
      - "README.md"
      - "docu/**"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Set up awesome-ci
        run: |
          wget https://github.com/eksrvb/awesome-ci/releases/latest/download/awesome-ci
          mv awesome-ci awesome-ci-latest
          chmod +x awesome-ci-latest
      - name: setup build Infos
        run: ./awesome-ci-latest getBuildInfos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build amd64
        run: go build -v -ldflags "-X main.version=$NEXT_VERSION" -o out/awesome-ci
        env:
          GOOS: linux
          GOARCH: amd64
      - name: Build arm64
        run: go build -v -ldflags "-X main.version=$NEXT_VERSION" -o out/awesome-ci-arm64
        env:
          GOOS: linux
          GOARCH: arm64
      - name: Print version of awesome-ci
        run: ./awesome-ci -version
      - name: Integration testing
        run: ./tools/test.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test writing dummy Release
        run: ./awesome-ci createRelease -patchLevel bugfix -dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
