name: Build PR

on:
  pull_request:
    paths-ignore:
      - 'README.md'
    types: [assigned, opened, synchronize, reopened, edited]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

#  test:
#    needs: setup
#    runs-on: ubuntu-latest
#    steps:
#    - name: Test
#      run: go test -v ./...

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - run: ls -l
    - run: ls -l ../
    - name: Build
      run: go build -o "out/" ../
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        path: out/