name: Publish Release

on:
  push:
    branches:    
    - 'master'
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Build
      run: go build -v
    - name: Create Release
      run: ./awesome-ci createRelease -uploadArtifacts awesome-ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
