name: Publish Release

on:
  push:
    branches:    
    - 'master'
    paths-ignore:
      - 'README.md'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: go build -v
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        path: awesome-ci
    - name: Create Release
      run: ./assets/awesome-ci-semver createRelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
