name: Publish Release

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "tests/**"
      - "go.**"
      - "**.go"
      - "Makefile"

jobs:
  generate_infos:
    runs-on: ubuntu-latest
    outputs:
      releaseid: ${{ steps.tag.outputs.releaseid }}
      version: ${{ steps.tag.outputs.version }}
      pr: ${{ steps.tag.outputs.pr }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup awesome-ci
        uses: fullstack-devops/awesome-ci-action@main

      - name: collect infos and create release
        run: |
          awesome-ci pr info
          awesome-ci release create
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: collect infos
        id: tag
        shell: bash
        run: |
          echo "::set-output name=version::$ACI_VERSION"
          echo "::set-output name=pr::$ACI_PR"
          echo "::set-output name=releaseid::$ACI_RELEASE_ID"

  build:
    runs-on: ubuntu-latest
    needs: generate_infos
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build "${{ matrix.arch }}"
        run: go build -v -ldflags "-X main.version=${{ needs.generate_infos.outputs.version }}" -o out/awesome-ci_${{ needs.generate_infos.outputs.version }}_${{ matrix.arch }}
        env:
          GOOS: linux
          GOARCH: "${{ matrix.arch }}"

      - name: Cache build outputs
        uses: actions/cache@v2
        env:
          cache-name: cache-outputs-modules
        with:
          path: out/
          key: awesome-ci-${{ github.sha }}-${{ hashFiles('out/awesome-ci*') }}
          restore-keys: |
            awesome-ci-${{ github.sha }}
      #- name: Integration testing
      #  run: ./tools/test.sh ./out/awesome-ci_${ACI_NEXT_VERSION}_${{ matrix.arch }}
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_release:
    runs-on: ubuntu-latest
    needs: [generate_infos, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup awesome-ci
        uses: fullstack-devops/awesome-ci-action@main

      - name: get cached build outputs
        uses: actions/cache@v2
        env:
          cache-name: cache-outputs-modules
        with:
          path: out/
          key: awesome-ci-${{ github.sha }}

      - name: list generated artifacts
        working-directory: out
        run: ls -la

      - name: Publish Release
        run: awesome-ci release publish -releaseid "$ACI_RELEASE_ID" -assets "file=out/$ARTIFACT1,file=out/$ARTIFACT2"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACI_RELEASE_ID: ${{ needs.generate_infos.outputs.releaseid }}
          ARTIFACT1: awesome-ci_${{ needs.generate_infos.outputs.version }}_amd64
          ARTIFACT2: awesome-ci_${{ needs.generate_infos.outputs.version }}_arm64

  update_action:
    runs-on: ubuntu-latest
    needs: [generate_infos, publish_release]
    steps:
      - name: Check out awesome-ci-action
        uses: actions/checkout@v2
        with:
          repository: fullstack-devops/awesome-ci-action
          token: ${{ secrets.ACI_REPO_TOKEN }}
          persist-credentials: true

      - name: Update version and push
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          OLD_VERSION=$(echo "$(git describe --tags)" | tr -d '\n')

          sed -i "s/$OLD_VERSION/$NEW_VERSION/g" action.yml README.md

          git status
          git commit -a -m "update to version v$NEW_VERSION"
          git tag v$NEW_VERSION -m "update to version v$NEW_VERSION"
          git push --follow-tags
        env:
          NEW_VERSION: ${{ needs.generate_infos.outputs.version }}
